### ISSUE TITLE
Excellent Code, just found one deprecated and one bug.

### ISSUE THREAD

**Issue by good-ghost** [trustin/smi2ass#1]
Thanks for excellent code!
I forked your code for make smi2srt, and just found below issues.

1. line 341,
    With 3.7 version og python, parser.unescape method is deprecated and need to replace with html.unescape.

2. seperate_by_lang method did not work, because bs4.find() function return a array of result but your code expect a string in line 385. just replace '[languageTag]' to '[languageTag[0]]'.

**Comment by trustin** [comment]
Thanks for suggestion. Would you mind sending a pull request? I'd be happy to accept yours!

By the way, I'm using a modified version of https://github.com/ncianeo/smi2srt for smi-to-srt conversion: https://gist.github.com/trustin/d69c097c8a1f8de8516b6dd475479ac4 (Removed separate-by-language feature because I never use it.)

**Comment by trustin** [comment]
Fixed via #2. Thanks, @good-ghost!
